### ISSUE TITLE
伙计 有更新吗？

### ISSUE THREAD

**Issue by junshenshi** [helpcode/KuaiShou#3]
好像现在快手无法操作了，可以更新下吗？

**Comment by helpcode** [comment]
现在快手换接口了，我有最新版的接口只是没发而已！！

**Comment by helpcode** [comment]
> 好像现在快手无法操作了，可以更新下吗？

现在更新的只是我整理好的文档，后端爬的程序也用nodejs写好了，只是源码没有提交到git，感兴趣可以自己根据我的文档写后端或者联系我直接用我的，晚点我把程序上传上来
